ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER visitsusr IDENTIFIED BY "visitspwd"
  DEFAULT TABLESPACE VISITS_MAIN
  TEMPORARY TABLESPACE VISITS_TEMP
  QUOTA UNLIMITED ON VISITS_MAIN
;

GRANT CONNECT TO visitsusr;
GRANT RESOURCE TO visitsusr;
GRANT CREATE VIEW TO visitsusr;
GRANT CREATE MATERIALIZED VIEW TO visitsusr;
GRANT CREATE SYNONYM TO visitsusr;
GRANT SELECT_CATALOG_ROLE TO visitsusr;
GRANT ANALYZE ANY TO visitsusr;
