ALTER SESSION SET CONTAINER = ORCLPDB1;

ALTER SESSION SET CURRENT_SCHEMA = VISITSUSR;

CREATE TABLE VISITS
(
    ID NUMBER GENERATED AS IDENTITY
        CONSTRAINT VISITS_PK
            PRIMARY KEY,
    WHEN TIMESTAMP(6) NOT NULL
)
    /

